spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/documents/**
          filters:
            - AddRequestHeader=X-Gateway, true

        - id: rag-service
          uri: lb://rag-service
          predicates:
            - Path=/ask/**

server:
  port: 8080

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    prefer-ip-address: true
