# ==========================================
# Server
# ==========================================
server.port=8083
spring.application.name=rag-service


# ==========================================
# PostgreSQL
# ==========================================
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/rag_vector
spring.datasource.username=postgres
spring.datasource.password=Vamshi@1309


# ==========================================
# OpenAI
# ==========================================
spring.ai.openai.api-key=${OPENAI_API_KEY}


# ==========================================
# PGVector
# ==========================================
spring.ai.vectorstore.pgvector.initialize-schema=true


# ==========================================
# Eureka
# ==========================================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
